define(function(require,exports,module){

return function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;

buf.push("<div class=\"filter\"><div class=\"filter__route-item\"><svg class=\"icon icon-switch\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-switch\"></use></svg><svg class=\"icon icon-fo-icon-2 icon-grid-display\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-fo-icon-2\"></use></svg><i class=\"icon icon-grid-display\"></i></div><div id=\"search\" class=\"filter__search\"><input type=\"text\" placeholder=\"\" class=\"search__text-field js-search__text-field\"/><div class=\"search-drop search-drop--filter js-search-drop is-hidden\"></div></div><div data-action=\"sale\" class=\"filter__item js-filter__item filter__action-item\"><i><svg class=\"icon icon-badge\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-badge\"></use></svg></i><span class=\"fi-text\">Акции</span></div><div data-action=\"collection\" class=\"filter__item js-filter__item filter__col-item\"><i><svg class=\"icon icon-collection\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-collection\"></use></svg></i><span class=\"fi-text\">Коллекции</span></div><div data-action=\"event\" class=\"filter__item js-filter__item filter__events-item\"><i><svg class=\"icon icon-calendar\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-calendar\"></use></svg></i><span class=\"fi-text\">События</span></div><div data-action=\"news\" class=\"filter__item js-filter__item filter__news-item\"><i><svg class=\"icon icon-rupor\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-rupor\"></use></svg></i><span class=\"fi-text\">Новости</span></div><div class=\"filter__favor js-filter__favor\"><div class=\"badge badge--favor\"><div class=\"badge__bottom\"></div><svg class=\"icon icon-star badge__ico badge__ico--favor\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-star\"></use></svg></div></div><div class=\"filter__droplist-item\"><div class=\"filter__droplist-point js-filter__droplist-point\"><i class=\"filter__droplist-ico\"></i><span class=\"fi-text\">Категории</span></div><div class=\"filter-droplist js-filter-droplist is-hidden\"><ul class=\"filter-droplist__list\"></ul></div></div><div class=\"filter__cleaning js-filter__cleaning\"><span class=\"fi-text\">Очистить фильтр</span><i><svg class=\"icon icon-close\"><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#icon-close\"></use></svg></i></div></div>");;return buf.join("");
};

});
